#!/usr/bin/env python3
"""Reformulation arm for the S (vocab-gap) diagnosis — the product-aligned lever.

roux serves LLM agents, and a real agent reformulates a plain question into the
code's jargon before searching. This measures that lever on the FROZEN held-out
S bucket: for each S query, fire blind agent-generated jargon variants at the
frozen snapshot via `roux query --also` (reciprocal-rank fused, one call), and
score the same way heldout_eval.py does (strict_match on gold in top-K).

Blindness: the variants in bench/vocab_gap_variants.json were generated by a
stateless model given ONLY the repo domain + the human query text — never the
gold symbol, never index access (see bench/vocab_gap_blind_input.json for the
exact generator input). This mirrors bench/agent_reform_eval.py's methodology,
generalized from 8 hand-picked Marlin queries to all 76 frozen S queries.

Usage:
    python3 bench/vocab_gap_reform.py [source ...]

Reports S Hit@1/5/10 + MRR per source and combined, next to the lexical
baseline (heldout_eval.py) and the dense ceiling (vocab_gap_dense.py).
"""
from __future__ import annotations

import glob
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

BENCH = Path(__file__).resolve().parent
sys.path.insert(0, str(BENCH))
import bench_match  # noqa: E402  # strict_match, mirrors heldout_eval

ROOT = BENCH.parent
ROUX = ROOT / "target" / "release" / "roux"
SNAPSHOTS = BENCH / "snapshots"
TOPK = 10


def load_s_queries(only: set[str] | None) -> list[dict]:
    out = []
    for fp in sorted(glob.glob(str(BENCH / "gold_*.frozen.json"))):
        d = json.load(open(fp))
        src = d["source_name"]
        if only and src not in only:
            continue
        for q in d.get("queries", []):
            if q.get("bucket") == "S":
                out.append({"id": q["id"], "source": src, "query": q["query"], "gold": q["gold"]})
    return out


def run_multi(source: str, variants: list[str], top: int = TOPK) -> list[str]:
    snap = SNAPSHOTS / f"{source}.sqlite"
    cmd = [str(ROUX), "query", variants[0]]
    for v in variants[1:]:
        cmd += ["--also", v]
    cmd += ["--db", str(snap), "--format", "json", "--top", str(top)]
    p = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    try:
        data = json.loads(p.stdout)
    except json.JSONDecodeError:
        return []
    return [s.get("qualified_name") or s.get("name", "") for s in data.get("symbols", [])][:top]


def main() -> None:
    only = set(sys.argv[1:]) or None
    variants_by_id = {
        r["id"]: r["variants"]
        for r in json.load(open(BENCH / "vocab_gap_variants.json"))["results"]
    }
    queries = load_s_queries(only)

    per_src = defaultdict(lambda: {"n": 0, "h1": 0, "h5": 0, "h10": 0, "mrr": 0.0})
    per_query = []
    print("=== REFORMULATION ARM (--also / RRF, blind variants) — S bucket ===")
    for q in queries:
        variants = variants_by_id.get(q["id"]) or [q["query"]]
        names = run_multi(q["source"], variants)
        rank = next((r + 1 for r, nm in enumerate(names)
                     if any(bench_match.strict_match(nm, g) for g in q["gold"])), None)
        d = per_src[q["source"]]
        d["n"] += 1
        if rank:
            d["h1"] += rank <= 1
            d["h5"] += rank <= 5
            d["h10"] += rank <= 10
            d["mrr"] += 1.0 / rank
        per_query.append({"source": q["source"], "query": q["query"], "gold": q["gold"], "rank": rank})

    tot = {"n": 0, "h1": 0, "h5": 0, "h10": 0, "mrr": 0.0}
    for src in sorted(per_src):
        d = per_src[src]
        for k in tot:
            tot[k] += d[k]
        print(f"  {src:8} n={d['n']:2}  Hit@1 {d['h1']:2}/{d['n']:<2} "
              f"Hit@5 {d['h5']:2}/{d['n']:<2} Hit@10 {d['h10']:2}/{d['n']:<2} MRR {d['mrr']/d['n']:.3f}")
    print(f"  {'COMBINED':8} n={tot['n']:2}  Hit@1 {tot['h1']:2}/{tot['n']:<2} "
          f"Hit@5 {tot['h5']:2}/{tot['n']:<2} Hit@10 {tot['h10']:2}/{tot['n']:<2} "
          f"MRR {tot['mrr']/tot['n']:.3f}")
    out = BENCH / "results" / "vocab_gap_reform.json"
    out.parent.mkdir(exist_ok=True)
    combined = {**tot, "mrr": tot["mrr"] / tot["n"] if tot["n"] else 0.0}
    json.dump({"topk": TOPK, "combined": combined, "per_query": per_query}, open(out, "w"), indent=2)
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
